// @flatppl/web — deploy-specific site overlay.
//
// A deployment of the gallery (live.flatppl.org, or somebody else's host)
// has to carry its own legal notice and similar pages, and those differ
// per deployment. They therefore live OUTSIDE this package — the public
// deploy's are in deploy/live.flatppl.org/site/ at the repo root — in an
// overlay directory that the build renders:
//
//   <siteDir>/site.json        — manifest: ordered list of pages
//   <siteDir>/<page>.md        — one Markdown source per page
//
//   site.json:
//     { "pages": [ { "title": "Legal Notice", "source": "legal-notice.md" }, … ] }
//
// Each page renders to dist/<basename>.html (a standalone page sharing
// the gallery's look via page.css), and the ordered page list becomes
// the gallery's footer links — build.mjs bakes them into build-flags.js
// as __FLATPPL_CONFIG__.footerLinks, from which the shell renders its
// footer at boot. So a reuser has two knobs, both outside the shell:
//
//   - FLATPPL_SITE_DIR=<dir> npm run build   — their own overlay
//     (pages + footer); unset, the build ships neither;
//   - or, when embedding the shell in a page of their own, set
//     __FLATPPL_CONFIG__.footerLinks in their bootstrap to point the
//     footer at pages they host elsewhere.
//
// An overlay without site.json yields no pages and no footer links (the
// shell then hides the footer entirely).
//
// Markdown is rendered with `marked` — the same renderer the viewer uses
// for doc comments — so the pages can be kept as prose, adapted from the
// homepage's notices without a hand conversion to HTML.

import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { marked } from 'marked';

/** Read <siteDir>/site.json. A missing overlay or manifest is not an
    error — it is the "no site pages" configuration. */
export async function loadSiteConfig(siteDir) {
  const manifest = join(siteDir, 'site.json');
  if (!existsSync(manifest)) return { pages: [] };
  const cfg = JSON.parse(await readFile(manifest, 'utf8'));
  return { pages: Array.isArray(cfg.pages) ? cfg.pages : [] };
}

/** Validate the manifest's page entries and derive each page's output
    file. Pages are flat: `source` is a bare basename inside the overlay
    and the output is that basename with `.html`, so the footer link is
    a plain relative URL that works under any base path. */
export function sitePagesFromConfig(cfg) {
  return (cfg.pages || []).map((page, i) => {
    if (typeof page.title !== 'string' || !page.title.trim()) {
      throw new Error(`site.json: page #${i + 1} has no title`);
    }
    if (typeof page.source !== 'string' || !page.source.trim()) {
      throw new Error(`site.json: page "${page.title}" has no source`);
    }
    if (page.source.includes('/') || page.source.includes('\\')) {
      throw new Error(`site.json: page "${page.title}": source must be a basename inside the site directory`);
    }
    const stem = page.source.replace(/\.(md|markdown)$/i, '');
    return { title: page.title, source: page.source, out: stem + '.html' };
  });
}

export function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** The standalone page template. Same chrome as the gallery — a header
    bar whose title links back to the gallery, then the rendered content
    in a capped text column, then the same footer as the gallery. Styled
    by page.css (NOT style.css: the shell's html/body overflow:hidden
    would stop a long notice from scrolling). */
export function renderSitePage({ title, bodyHtml, footerLinks }) {
  const links = (footerLinks || [])
    .map((l) => `<a href="${escapeHtml(l.href)}">${escapeHtml(l.label)}</a>`)
    .join('\n      ');
  const t = escapeHtml(title);
  return `<!DOCTYPE html>
<!-- Generated by build-site.mjs from the site overlay. Do not edit. -->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${t} — FlatPPL</title>
  <link rel="stylesheet" href="page.css">
</head>
<body>
  <header id="page-header">
    <a id="page-home" href="./">FlatPPL</a>
  </header>
  <main id="page-main">
    <h1>${t}</h1>
${bodyHtml}
  </main>
  <footer id="page-footer">
      ${links}
  </footer>
</body>
</html>
`;
}

/** Render every page of the overlay at <siteDir> into <distDir> and
    return the footer links `[{ label, href }]` in manifest order. */
export async function buildSite({ siteDir, distDir }) {
  const pages = sitePagesFromConfig(await loadSiteConfig(siteDir));
  const footerLinks = pages.map((p) => ({ label: p.title, href: p.out }));
  for (const page of pages) {
    const src = join(siteDir, page.source);
    if (!existsSync(src)) {
      throw new Error(`site.json: page "${page.title}": ${src} not found`);
    }
    const md = await readFile(src, 'utf8');
    const bodyHtml = await marked.parse(md);
    await writeFile(join(distDir, page.out),
      renderSitePage({ title: page.title, bodyHtml, footerLinks }));
  }
  return footerLinks;
}
